id: ACAF63A40
title: Toh_134-The_Absorption_That_Encapsulates_All_Merit-v2
type: translation
pechas:
- I13757D66
- I551C44B8
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-056-002
  title: Toh_134-The_Absorption_That_Encapsulates_All_Merit-v2
alignment_to_base:
  I13757D66/2A75: '2778'
  I551C44B8/6A55: '2778'
